/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.coffey.app;


import org.coffey.Entry;

public class App {
    public static void main(String[] args) {
        int status = new Entry().main(args);
    }
}
