/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.5.21"
    java
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":library:core"))
}

tasks.shadowJar {
    manifest {
        attributes["Main-Class"] = "org.caffey.app.App"
    }
}