/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
    java
    id("com.github.johnrengelman.shadow") version "7.0.0"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":library:core"))
}

java {
    sourceCompatibility = org.gradle.api.JavaVersion.VERSION_1_9
    targetCompatibility = org.gradle.api.JavaVersion.VERSION_1_9
}

tasks.shadowJar {
    archiveBaseName.set("coffey")
    manifest {
        attributes["Main-Class"] = "org.coffey.app.App"
    }
}