/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.5.21"
    java
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":library:core"))
}

